### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by Aslaak** [Staartvin/Statz#1]
Hello,

I have a nullpointerexception error in my logs, i'm using spigot 1.10, this is the error : 

http://hastebin.com/ogexexumuj.avrasm

I hope it will help you to improve staz ! :)

**Comment by Staartvin** [comment]
Could you provide the whole stacktrace?

**Comment by Aslaak** [comment]
oh, sorry

I have this http://hastebin.com/uvebakilov.avrasm and http://hastebin.com/qucizatoja.avrasm
but I don't have the first error anymore, it's a bit strange :s

**Comment by Staartvin** [comment]
The first error was fixed in Statz 1.2.1, that's why you don't see it anymore ;)

**Comment by Staartvin** [comment]
If you haven't already, please upgrade to Statz 1.2.1!

**Comment by Aslaak** [comment]
it works, now I have this error (using last spigot build)

http://hastebin.com/etebivarul.apache

it looks like to happens when I execute command
(sorry for my english btw)
