### ISSUE TITLE
[bug] Loads of errors on fresh Statz install.

### ISSUE THREAD

**Issue by FrozenBeard** [Staartvin/Statz#101]
Doing a clean install on a 1.13.2 server, there are errors and its trying to patch a database? But its the initial setup of the database, how on earth is it trying to patch it?

https://gist.github.com/FrozenBeard/2acd6c9ff5e6c5d73fc548b9f63ccf5e

I added the plugin, which by default creates an SQLite file, I stopped the server, added the MySQL config options and started the server, it created the MySQL tables fine, but theres all these errors and patching which shouldn't be happening on a fresh, clean install.

**Comment by Staartvin** [comment]
Does it happen with both SQlite and MySQL?

**Comment by FrozenBeard** [comment]
I would assume so, Its a long time since I created this ticket, I would be using MySQL.

**Comment by Staartvin** [comment]
I fixed this issue in the latest version of Statz. It was related to trying to patch the database even though that was needed.
