### ISSUE TITLE
Massive errors caused by the plugin Statz

### ISSUE THREAD

**Issue by MrTracer** [Staartvin/Statz#105]
![Screen_Shot_2019-06-07_at_10 29 13_AM](https://user-images.githubusercontent.com/51485482/59111743-f0f55400-8941-11e9-9a21-87f8fb6fd3b4.png)

These errors are crashing my minecraft server.
I have 2 issues with it.
1. Uninstalling it does not work, it reinstall's itself.
2. The errors from the screenshot above.
Can you please help.

**Comment by Staartvin** [comment]
This issue should be fixed in the latest version of Statz. Download it and test it!
