### ISSUE TITLE
InventoryCreativeEvent error

### ISSUE THREAD

**Issue by Tantillus-KW1C** [Staartvin/Statz#110]
Hey,

Statz doesn't like anyone removing/adding/picking up anything from their inventories.
Statz 1.5.3 
In combination with [these](http://prntscr.com/ozadl5) plugins.
Edit: Related issue: #109 

Console output:
https://paste.helpch.at/aqarayujig.rb
And:
https://paste.helpch.at/vijegusawa.rb

Thanks.

**Comment by Staartvin** [comment]
This issue should be fixed in the latest version of Statz. Could you try to test it with this version?
