### ISSUE TITLE
Players can pull the items out of the GUI

### ISSUE THREAD

**Issue by souldin** [Staartvin/Statz#112]
When using the GUI Players can pull the items out of the GUI and use them. Can this be locked so they cannot happen as it is free stuff and can be done over and over.

**Comment by ZonkedCompanion** [comment]
I second this. 

Spigot 1.14.4.

The GUI does not function correctly. 

When you click an item it can be dragged from the GUI into player inventory. The sub menus do not work - ie when you click on blocks placed to see a break down of placed blocks nothing happens, you just pick up the item from the GUI.

Frustrating.

**Comment by Staartvin** [comment]
Did you try the latest version of Statz. Is this issue still occuring? I can't seem to reproduce it in the most recent version.

**Comment by Staartvin** [comment]
Please re-open this issue if the error still occurs on the latest version.
