### ISSUE TITLE
Vote tracking.

### ISSUE THREAD

**Issue by mickcoyne** [Staartvin/Statz#15]
nuvotifier is not working for me. 
the plugin works just fine, however statz does not work with it. In both Votifier and nuvotifier, Statz does notice the vote, however if you check the MySQL database no votes are logged and after the server restarts everyones vote count gets reset. No other issues with statz everything from playtime to mobs killed works fine except vote tracking

**Comment by Staartvin** [comment]
I'm working on getting votes fixed!
