### ISSUE TITLE
MySQLSyntaxErrorException: Specified key was too long

### ISSUE THREAD

**Issue by sliverpix** [Staartvin/Statz#17]
Ive had to rebuild/add many tables to the DB that did not get created during the install of statz. THANK GOD you made the wiki and added the table information!! THANK YOU for that.

This seems to be the only one I cant find. Im pretty sure its a field that should be set to VARCHAR or something similar, but i cant seem to figure out which one... OR... its something else entirely. I could use your help. Below is an excerpt from the log:

http://pastebin.com/e8fRM29t

**Comment by Staartvin** [comment]
What stat is it erroring on?

**Comment by sliverpix** [comment]
I have no idea. hence why i was asking for help. I cant seem to figure it out... it always shows up right after "Save Statz database."
