### ISSUE TITLE
[feature] bungee support

### ISSUE THREAD

**Issue by feardevilz** [Staartvin/Statz#20]
I was hoping you could add bungeecord drop in support but I'm unsure if all features would be sent to the proxy for stats recording such as block breaks or mmo skills. I was simply looking for an central singular stats drop in aside from maintaining it on each server.

**Comment by Staartvin** [comment]
Statz should already support Bungee!

**Comment by feardevilz** [comment]
Actually @Staartvin, it looks like this is not able to be dropped into the bungee plugins folder as it pulled bukkit api. This feature was to have a bungee version which can be placed inside the bungee proxy plugins folder and not the bukkit ones to enable network-wide statz collection. 

Sorry for any misunderstanding on the original request. Can you please let me know if you would consider supporting that?

**Comment by Staartvin** [comment]
Hmm, so when installed on a bungee server, Statz refuses to run?

**Comment by feardevilz** [comment]
@Staartvin I added some additional data on the errors i saw.

**Comment by michaeldriskell** [comment]
I have statz on all of the servers on my bungee server and they're all synced to the same SQL database. That's "bungee support"

**Comment by NotStarRift** [comment]
I was going to say basically any plugin that has SQL support is as good as having "bungee support". I actually prefer I keep the main proxy clear of unecessary plugins anyway.
