### ISSUE TITLE
migration/import from other stats plugins

### ISSUE THREAD

**Issue by feardevilz** [Staartvin/Statz#21]
Hey, I was wondering if you can add in a migration section from other stats-based plugins to Statz. The oldest one I've seen which is still widely used is: https://dev.bukkit.org/bukkit-plugins/lolmewnstats/. I'd love to see migration from that plugins sql to yours added as well as a possible different web interface to support use on the web.'

Edit - source is: https://bitbucket.org/Lolmewn/stats

**Comment by Staartvin** [comment]
Yup, I'll be working on a converter from Stats to Statz!

**Comment by Staartvin** [comment]
Should be added in https://github.com/Staartvin/Statz/commit/1970e48c7532be9c16be9386f6e66ce41ed4d4fe.
