### ISSUE TITLE
MySQL time out 

### ISSUE THREAD

**Issue by ssamjh** [Staartvin/Statz#28]
Server log: https://paste.ssamjh.nz/view/raw/d2f26677

Spigot 1.11 with Statz 1.4

**Comment by dutchy1001** [comment]
I have same issue
http://pastebin.com/MBQCBG0C

I use PaperSpigot 1.11.2 and Statz 1.4 too

**Comment by dutchy1001** [comment]
I havent see this error since updating to v4.0.

Great work

**Comment by leventinio** [comment]
Hello, i have the same Problem, after a time the Server is crashing.

https://hastebin.com/ruquyidotu.md
