### ISSUE TITLE
 Could not pass event EntityDeathEvent - Method Exception

### ISSUE THREAD

**Issue by Rubbertjuh** [Staartvin/Statz#3]
Hello, 
Whenever a player dies you will see this error in the console:
http://hastebin.com/tixoneqoqa.avrasm

I'm sure on a larger server, that this is getting very spammy. 
Running on CB 1.7.10 - Forge - Thermos server software (Cauldron fork)

If you need more information, please let me know.

**Comment by Staartvin** [comment]
Could you try this build of Statz? http://62.131.38.74:8080/job/Statz/49/
