### ISSUE TITLE
Statz reporting UUID was not found in the stats database?

### ISSUE THREAD

**Issue by FrozenBeard** [Staartvin/Statz#31]
Im using Autorank v3.8.5.1, Stats3 from lolmewnstats and I have Statz 1.4, I have stat recording disabled on Statz as im using Stats3, It is going absolutely mental in the console spamming the console with this error message;
`[Statz debug] UUID '134cef20-e16b-429c-ae0a-ac5a5ffdf6a7' was not found in Stats database!`
I assume for every user, Now I have no idea if thats reffering to Statz or stats3 as it just says Stats Database, Now my Stats3 database definitely has all the UUID's of the players, and Statz shouldn't be touching it, as I don't want it recording data.
What is going on? Why is this doing this? I really really really wanted to get my god damn Stats3 and Autorank updated today after failign to get it done at the weekend, and yet again there is another error stopping me.

**Comment by Staartvin** [comment]
Did you try to migrate data from Stats 3 to Statz?

**Comment by FrozenBeard** [comment]
This isn't an option at present, just not right now. I told you this on the Autorank github.

1. It shouldn't even need Statz as stats3 is supported, again PLEASE listen.
2. My Database is INSANE in size, like its a GIG, I have been trying to convert from stats2 for about 2 years now, but the time it takes to convert from stats2 to stats3 is literally multiple days, I set aside this time to convert the database from stats2 to stats3, and get all the database migrated and stats3 updated. Im litearllyt down to an hour left today and im having to answer the same questions I have already.
3. Statz is NOT ready for production there are so many things that need to happen before its stable, I WILL reply to your comment with a massive list of what needs to change, but I CANT do that until I can actually get off stats2 and update to the latest autorank, Im literally stuck with your stubbornness, JUST LET ME GET OFF STAS2, and then we can think about moving to statz.
4. I haven't tested your statz conversion, I will not just randomly trust that it will work 100% first time, and my bet is this will take days to convert too.

please will you just help me out, I need to get off stats2 to stats3, I have done the conversion, I work full time and have timed this database converson to end today in the time I have 2 hours free, now i only have an hour freee and im having to battle statz yet again, I cannot belive im going to have to wait another week and do anoter conversion as every single time I go to do this update I get stuck with autorank or statz.

**Comment by FrozenBeard** [comment]
Im really running short on time here, If I cant get this all updated today, I then need to wait until I can next do it, which means I then need to reconvert the stats2 to stats3 database, which takes 2 days, Each time I need to prepair the database, it takes a very long time. I just need Stats3 to work as it should. is there any way I can get an explanation to why this is happening to see if I can do something to stop it, I have been trying as much as I can think of, I haven't run Statz conversion, this isnt an option at present, I cant run a conert to another convert there is way way too much that can go wrong, let alone the time it takes, it needs to settle with stats3 for a bit before I even tackle and test a Statz conversion, please I really need an explanation and a fix.

**Comment by Staartvin** [comment]
I know you want to use  Autorank 3.8.5.1, and that version still has Stats 3 support. Since you are planning on using that, I can help you set stuff up if you like. Although I don't want to get in your way of running a server, I cannot support Stats 2 anymore. I've discussed this with lolmewn, the developer of Stats, and he basically said that Stats 3 is far more stable and efficient. If you need help converting to Stats 3, I can help. 

Furthermore,  I'm eager to work on Statz to improve it when you finished converting and wrote a list. I just want to stress that I do not want to get in your way of running your server, I'm just supporting the most sensitive thing.

**Comment by Staartvin** [comment]
If you need my 'live'  help,  please contact me on Skype (Staartvin).

**Comment by FrozenBeard** [comment]
You are not listening, Im not talking about a Statz conversion the Stats3 does its own conversion from Stats2, please read what im saying to you. I am **not** asking for a stats2 conversion, stats3 does this.
Again please go back and READ my ticket and with it in mind that I am talking about the **lolmewn Stats2** conversion from the **lolmewn Stats 3**. 
I have added you on skype you are not replying.

Please just listen to what im writing, how can I make this simler to understand.
I have spent 48 hours converting from lolmewn stats2 to lolmewn stats3, I have my lolmewn stats 3 working in-game, I have Autorank  3.8.5.1 working with the converted data (I think, I cant check as Im now stuck with this). To use  Autorank  3.8.5.1 I am forced to use **Statz** so I have BOTH **Statz** AND **lolmewn stats 3** on my server so I can get **Autorank**  working, I have disabled statistic recording with **Statz** as I am using **lolmewn stats 3** temporarily until Statz is stable. 

The issue I am having is Statz is trying to do something it shouldn't, it should only be acting as a Hook, but it is trying to look up UUID's in its own database?!?! I have told it NOT to record statistics and I am getting this error, which I posted in the first ticket.

**Comment by Staartvin** [comment]
I know you are trying to convert from Stats 2 to Stats 3, that part was already clear to me. Im looking into the source of Statz right now to see why it is outputting those messages.

**Comment by FrozenBeard** [comment]
All my data has finished converting to stats 3, thats all you have to worry about, Im not asking for a Stats2 conversion. Im telling you this as context as to why it isnt the time to upgrade to Statz.
Thank you for looking, this has got me incredibly stressed, as it takes so much preparation and time, and I just want this done, every time I go to push this to production I test it one last time and more errors keep coming up.

**Comment by FrozenBeard** [comment]
https://github.com/Staartvin/Statz/blob/fb7c6bd757eedd60d93d3ffea3550f2a88f4ea61/src/me/staartvin/statz/hooks/handlers/StatsAPIHandler.java#L204

**Comment by FrozenBeard** [comment]
@Staartvin Was this issue fixed in a new release? I'm still stuck where I am until the issues discussed are fixed!

**Comment by Staartvin** [comment]
Whoops, sorry! I'm working on it right now!
