### ISSUE TITLE
The permission nodes: "statz.list.self", and "statz.list.others" are not working in Statz v1.4

### ISSUE THREAD

**Issue by LandGridArray** [Staartvin/Statz#33]
Hello, Staartvin. There seems to be an issue with your plugin "Statz" version 1.4 in relation to its permission nodes. Stat tracking works great, and I love the amount of statistics it has the capability to track, though some of the permissions are not being registered through PermissionsEx. I have the permission node statz.list.self in all groups (yes, I've checked its spelling, along with formatting), though it does not seem to register. In the event a player attempts to perform the command "statz list", they are simply greeted with the message: "You do not have the permission () to perform this command." Also, all the other permission nodes aside from "statz.list.self/others" work as advertised, so I'm assuming the error is in relation with the new permission node scheme you implemented, which looks nice on paper I might add. In conclusion, I'm not entirety sure if I am required to install a prerequisite plugin that Statz requires, if it's incompatible with PermissionEx, or if it's a bug. Thank you, and I hope you find this information useful.

Also, I will post a server log below for your reference, along with a screenshot of the error message.

[reference1.txt](https://github.com/Staartvin/Statz/files/749329/reference1.txt)

![shref1](https://cloud.githubusercontent.com/assets/25518611/22575382/dd28b796-e97a-11e6-994a-dc90f057be04.png)

**Comment by Staartvin** [comment]
Thanks for the valuable feedback! I have looked into this issue and I can reproduce this. I'm currently working on a fix!

**Comment by Staartvin** [comment]
Could you try this test build to see if it's fixed?
http://178.62.255.148:8080/job/Statz/27/

**Comment by LandGridArray** [comment]
Thank you for working on a hot fix, I greatly appreciate it! Once I get home from school (around 4:00 PM, Central Standard Time), I will quickly test your fix. Again again, thank you.

**Comment by LandGridArray** [comment]
Apologies for sounding inexperienced in the event there is an obvious solution to my question. Though, how would I gain access to your file through Jenkins? I clicked on the link you listed in your previous comment, but I was greeting with a login screen. I'm not sure if there's a default username/password I'm supposed to input, if I'm supposed to perform a UNIX command with the link as a parameter, or if I'm completely off and there's something other I'm required to do.
