### ISSUE TITLE
Mysql issues

### ISSUE THREAD

**Issue by ChromaHosting** [Staartvin/Statz#34]
01.02 15:11:52 [Server] ERROR [Statz] MySQL exception on initialize: Access denied for user 'root'@'localhost' (using password: YES)
and spamming of [Statz debug] Save Statz database. in console

please reply quickly its freaking annoying

**Comment by ChromaHosting** [comment]
I'm using statz 1.4.2

**Comment by Staartvin** [comment]
You are not entering the correct username/password combination, or your database is not configured to be controlled remotely.

**Comment by ChromaHosting** [comment]
I am entering the correct things, my mc servers and mysql server run on the same vps all my other pugins connect to the same database perfectly fine.

**Comment by Staartvin** [comment]
Hmm. Are you sure your root user has the correct privileges to access the database? Can you also double check if you entered the credentials in the Settings.yml correctly? (Compare it with other plugins credentials that does work).

**Comment by ChromaHosting** [comment]
Every other plugin connects with the same user and same pasword

**Comment by ChromaHosting** [comment]
is the password meant to be surrounded by **'** ?

**Comment by Staartvin** [comment]
You can try removing those quotation marks.

**Comment by ChromaHosting** [comment]
i removed them when adding the password origonally

**Comment by Staartvin** [comment]
Then try putting them back hehe

**Comment by ChromaHosting** [comment]
ok

**Comment by ChromaHosting** [comment]
nope didn't fix it

**Comment by Staartvin** [comment]
Then, I wouldn't really know. Can you perform an /ar debug and provide me the file?

**Comment by Staartvin** [comment]
Can you perform **/version Autorank**?

**Comment by ChromaHosting** [comment]
i don't have autorank
i have no need for it

**Comment by ChromaHosting** [comment]
and show database save message: false isn't stoping it from spamming [Statz debug] Save Statz database.

**Comment by Staartvin** [comment]
Ah, sorry. What version of Statz are you running then?

**Comment by ChromaHosting** [comment]
1.4.2

**Comment by ChromaHosting** [comment]
i updated from 1.4 today

**Comment by ChromaHosting** [comment]
the problem exsisted in 1.4

**Comment by Staartvin** [comment]
Hmm, can you test SQLite and see if that works? Then we can rule out it's something with the Database connector altogether.

**Comment by ChromaHosting** [comment]
ok

**Comment by ChromaHosting** [comment]
how do i switch to sqlite?

**Comment by Staartvin** [comment]
You can switch the settings in the config.yml :)

**Comment by ChromaHosting** [comment]
i set enabled (user mysql) to false but it seems to be trying to connect to mysql still

**Comment by ChromaHosting** [comment]
it also shot out a load of sqlite driver errors

**Comment by ChromaHosting** [comment]
no matter what I change in the config.yml nothing chnages

**Comment by ChromaHosting** [comment]
i just tried completely deleting the plugin and re-installing it and all that did was regen the config with everything i had already entered

**Comment by Staartvin** [comment]
Hmm, can you stop the server. Then set to sqlite, delete the sqlite database in the Statz folder and restart the server.

**Comment by ChromaHosting** [comment]
just to make sure.. the config file is called config.yml (you said settings.yml earlier)

**Comment by ChromaHosting** [comment]
stopping the server setting it to sqlite and starting it again worked

**Comment by ChromaHosting** [comment]
Switched back to MySQL and all is working

**Comment by ChromaHosting** [comment]
thank you :P

**Comment by Staartvin** [comment]
Great, glad I could help!
