### ISSUE TITLE
Support for Battlelevels

### ISSUE THREAD

**Issue by Keystirras** [Staartvin/Statz#36]
Hello, your plugin looks amazing, but it would really help me and my server if you added support for Battlelevels!

https://www.spigotmc.org/resources/battlelevels.2218/

Thanks!

**Comment by Staartvin** [comment]
I will look into it!

**Comment by Keystirras** [comment]
Hey any update?

**Comment by Staartvin** [comment]
BattleLevels will be supported in the next version!
