### ISSUE TITLE
Conflict with ASkyblock

### ISSUE THREAD

**Issue by cmorda** [Staartvin/Statz#4]
ASkyblock has a default setting that places a cow or other animal on a player's new island with a name that includes an apostrophe. 

I don't know exactly what is happening in the plugin but the apostrophe appears to be interpreted as a single quote when writing to the SQL server. 

Here is a snippet of the log. http://hastebin.com/yahuxeqiko.vbs

I am using the latest version of Statz. ASkyblock is version 3.0.1.1 (one version behind).

Thanks for your awesome stats plugin.

**Comment by Staartvin** [comment]
Ah thanks for reporting! Can you show me a picture of the animal in question?

**Comment by Staartvin** [comment]
This build should fix it: http://62.131.38.74:8080/job/Statz/49/
