### ISSUE TITLE
Statz transfer not working

### ISSUE THREAD

**Issue by krustymk** [Staartvin/Statz#41]
[log-2017-03-12-09-07-37.txt](https://github.com/Staartvin/Statz/files/836849/log-2017-03-12-09-07-37.txt)
A log from today(tried several times over the course of today), it seems to be saving new data and updating the tables but will not transfer the old data

**Comment by Staartvin** [comment]
Did you use the /Statz migrate command?

**Comment by krustymk** [comment]
/statz transfer
as far as i could thats how i read the instructions 
to move from statz flatfile to MYSQL database

**Comment by Staartvin** [comment]
Could you try to stop the server and restart it, then start the transfer but prevent any users from logging in while transferring?

**Comment by krustymk** [comment]
Ive tried that several times, it never starts. i recieve the following notification but no tables have any data added to them
19.03 22:20:39 [Server] INFO Transferring database records... This make take a while!
19.03 22:20:39 [Server] INFO Transferred 0 database records from SQLite to MySQL!
19.03 22:20:39 [Server] INFO [Statz debug] Loaded table 'statz_players'
19.03 22:20:39 [Server] INFO [Statz debug] Loaded table 'statz_joins'
19.03 22:20:39 [Server] INFO [Statz debug] Loaded table 'statz_deaths'
19.03 22:20:39 [Server] INFO [Statz debug] Loaded table 'statz_items_caught'
19.03 22:20:39 [Server] INFO [Statz debug] Loaded table 'statz_blocks_placed'
19.03 22:20:39 [Server] INFO [Statz debug] Loaded table 'statz_blocks_broken'
19.03 22:20:39 [Server] INFO [Statz debug] Loaded table 'statz_kills_mobs'
19.03 22:20:39 [Server] INFO [Statz debug] Loaded table 'statz_kills_players'
19.03 22:20:39 [Server] INFO [Statz debug] Loaded table 'statz_time_played'
19.03 22:20:39 [Server] INFO [Statz debug] Loaded table 'statz_food_eaten'
19.03 22:20:39 [Server] INFO [Statz debug] Loaded table 'statz_damage_taken'
19.03 22:20:39 [Server] INFO [Statz debug] Loaded table 'statz_times_shorn'
19.03 22:20:39 [Server] INFO [Statz debug] Loaded table 'statz_distance_travelled'
19.03 22:20:39 [Server] INFO [Statz debug] Loaded table 'statz_items_crafted'
19.03 22:20:39 [Server] INFO [Statz debug] Loaded table 'statz_xp_gained'
19.03 22:20:39 [Server] INFO [Statz debug] Loaded table 'statz_votes'
19.03 22:20:39 [Server] INFO [Statz debug] Loaded table 'statz_arrows_shot'
19.03 22:20:39 [Server] INFO [Statz debug] Loaded table 'statz_entered_beds'
19.03 22:20:39 [Server] INFO [Statz debug] Loaded table 'statz_commands_performed'
19.03 22:20:39 [Server] INFO [Statz debug] Loaded table 'statz_times_kicked'
19.03 22:20:39 [Server] INFO [Statz debug] Loaded table 'statz_tools_broken'
19.03 22:20:39 [Server] INFO [Statz debug] Loaded table 'statz_eggs_thrown'
19.03 22:20:39 [Server] INFO [Statz debug] Loaded table 'statz_worlds_changed'
19.03 22:20:39 [Server] INFO [Statz debug] Loaded table 'statz_buckets_filled'
19.03 22:20:39 [Server] INFO [Statz debug] Loaded table 'statz_buckets_emptied'
19.03 22:20:39 [Server] INFO [Statz debug] Loaded table 'statz_items_dropped'
19.03 22:20:39 [Server] INFO [Statz debug] Loaded table 'statz_items_picked_up'

**Comment by Staartvin** [comment]
Can you provide your config and sqlite database?

**Comment by krustymk** [comment]
New Well.. this may be part of the issue? After playing around (creating new server, databases, users.. bla bla) i noticed that when you do a /statz transfer for the first time you get the following error in the console 
http://pastebin.com/JLCeQEzH
and a new data base is created in the plugin folder named 'Stats.db', which i think the plugin looks in for data to transfer to the MYSQL database, ignoring the 'Statz.db'
Could it be as simple as a typo?
The database is to big for here, i can email it? I changed the config extension as yml isnt allowed, and what with editing out user/pass/database is probably useless anyway?

[config.txt](https://github.com/Staartvin/Statz/files/855070/config.txt)

**Comment by krustymk** [comment]
This is fixed now?

**Comment by Staartvin** [comment]
Could you try it again and see if it works now?
