### ISSUE TITLE
EntityDeathEvent to Statz v1.4.3

### ISSUE THREAD

**Issue by H4nSolo** [Staartvin/Statz#44]
Hello Developer,

on some versions of statz i have the EntityDeathEvent Error in my log.

System:
Ubuntu 16.04
Java 8
64GB Ram

Error log:  [pastebin](http://pastebin.com/nkNSncM0)

How i can fix that? Or is the plugin buggy?

**Comment by H4nSolo** [comment]
any help or reactions?

**Comment by Staartvin** [comment]
What version of Minecraft are you running? The latest version of Statz requires 1.10 or higher.
