### ISSUE TITLE
Statz keeps turning alerts back on.

### ISSUE THREAD

**Issue by Corcustos** [Staartvin/Statz#46]
I'm not sure what's going on, but every time I set my "show database save message" to false, the plugin keeps resetting it back to true upon restart. It's getting really annoying having the database spam my console. How do I fix this?

I'm using the following versions:
-Spigot 1.8.8
-Stats 1.4.2

If you need any additional information let me know. I know this was a bit brief, so hopefully I didn't miss anything. There are no Statz related errors upon restart either. The console log is clean of them.

Note: I haven't touched anything else in the configs for Statz besides what was mentioned above.

**Comment by Staartvin** [comment]
Try stopping your server, setting the option to false in the config and then starting your server. That should save it.

**Comment by Corcustos** [comment]
Oh. That was actually simple. I probably could've figured that out for myself, but thank you for the help. I feel like an idiot.

**Comment by Staartvin** [comment]
No problemo, glad I could help!
