### ISSUE TITLE
After plugin update, players who ranked up had their stats reset.

### ISSUE THREAD

**Issue by Zyrille** [Staartvin/Statz#47]
Hi there! I've recently updated the plugin to the newest version released on spigot, a few members after the update has ranked up and they noticed their requirements have been reset.

My server is setup in a way where:

Rank A:
Needs 100 blocks placed
Needs 100 blocks broken
Needs to kill 100 mobs

Rank B:
Needs 200 blocks placed
Needs 200 blocks broken
Needs to kill 100 mobs

As you can see it accumulates to be able to rank up, but my player's stats reset back to 0 when they ranked up.

Also, is there any command we can use where an administrator can manually change a player's stats (x block broken, x block placed and x mobs killed)?

**Comment by Staartvin** [comment]
Hmm, that's odd. I had no such problem. Are you sure you didn't connect Statz to a different database?

Unfortunately, there is no command to change the data. You'll need to edit it in your database yourself. I'm planning on adding it, but the syntax is rather complex.

**Comment by Zyrille** [comment]
It seems after trying to transfer my db the first time it created another statz.db and it doubled, which caused the reset. I've deleted the doubled database but I am now having problems connecting statz with mysql, no matter how much I tinker, I can't seem to get it right. 

It always gives me this error:

`04.06 04:24:47 [Server] ERROR MySQL exception on initialize: Could not create connection to database server. Attempted reconnect 3 times. Giving up. 04.06 04:24:47 [Server] INFO SQLDataStorage.connect 04.06 04:24:47 [Server] INFO SQLException: Could not create connection to database server. Attempted reconnect 3 times. Giving up. 04.06 04:24:47 [Server] INFO SQLState: 08001 04.06 04:24:47 [Server] INFO VendorError: 0 04.06 04:24:47 [Server] INFO I could not connect to your database! Are your credentials correct?`

And I am more than sure that the info I placed in the config file is correct, I triple checked and did it with two different hosts just to make sure the problem isn't with the host but to no avail.

**Comment by Staartvin** [comment]
Could you turn on debug and start up your server. I'm interested in the startup log of Statz with debug enabled.

**Comment by FrozenBeard** [comment]
Im having a bug where my playtime is being reset to 0 in my Stats3, Since Autorank pulls from Stats3, is it possible its autorank causing the resets of playtime?

**Comment by Staartvin** [comment]
Are you still experiencing this issue, @Zyrille ?
