### ISSUE TITLE
Common MySQL Issue?

### ISSUE THREAD

**Issue by Wasdspacemouse** [Staartvin/Statz#48]
Hi! I've seen many people have MySQL issues, but none of their solutions seem to be working for me. I have no idea what's causing this, so I'll just send you the error:

https://pastebin.com/AkG6e5Js

I spent a good 4 hours today trying to fix AutoRank, but I can't do it for the life of me. Thanks in advance for any help.

**Comment by Redstonetorch** [comment]
I have a very similar issue, I figured installing statz would fix it since I didnt have it previously and was trying to run requirements that required this plugin but now i have two issues... Let me know if you figure anything out lol

**Comment by Wasdspacemouse** [comment]
I did fix the issue, but I don't know how I did it. I'm pretty sure I just reinstalled Statz and didn't edit the MySQL section at all. It's been working fine now. But yea if that doesn't work I've got nothing for you, sorry.

**Comment by Redstonetorch** [comment]
Mk I'll give it a shot.. did you delete the folder for it as well or just the jar?

**Comment by Wasdspacemouse** [comment]
Yes I deleted the folder, that's probably the most important part. Luckily it's not a huge config.
