### ISSUE TITLE
fly error

### ISSUE THREAD

**Issue by xknat** [Staartvin/Statz#5]
i get this spamming message:
23.07 16:05:47 [Server] ERROR Could not pass event PlayerMoveEvent to Statz v1.1
23.07 16:05:47 [Server] INFO org.bukkit.event.EventException
23.07 16:05:47 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.10.2.jar:git-Spigot-cf6dea3-ca1bb1c]
23.07 16:05:47 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.10.2.jar:git-Spigot-cf6dea3-ca1bb1c]
23.07 16:05:47 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.10.2.jar:git-Spigot-cf6dea3-ca1bb1c]
23.07 16:05:47 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.10.2.jar:git-Spigot-cf6dea3-ca1bb1c]
23.07 16:05:47 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:610) [spigot-1.10.2.jar:git-Spigot-cf6dea3-ca1bb1c]
23.07 16:05:47 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInFlying.a(SourceFile:126) [spigot-1.10.2.jar:git-Spigot-cf6dea3-ca1bb1c]
23.07 16:05:47 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [spigot-1.10.2.jar:git-Spigot-cf6dea3-ca1bb1c]
23.07 16:05:47 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.10.2.jar:git-Spigot-cf6dea3-ca1bb1c]
23.07 16:05:47 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_45]
23.07 16:05:47 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_45]
23.07 16:05:47 [Server] INFO at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot-1.10.2.jar:git-Spigot-cf6dea3-ca1bb1c]
23.07 16:05:47 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:737) [spigot-1.10.2.jar:git-Spigot-cf6dea3-ca1bb1c]
23.07 16:05:47 [Server] INFO at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.10.2.jar:git-Spigot-cf6dea3-ca1bb1c]
23.07 16:05:47 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:673) [spigot-1.10.2.jar:git-Spigot-cf6dea3-ca1bb1c]
23.07 16:05:47 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:572) [spigot-1.10.2.jar:git-Spigot-cf6dea3-ca1bb1c]
23.07 16:05:47 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
23.07 16:05:47 [Server] INFO Caused by: java.lang.NullPointerException

**Comment by Staartvin** [comment]
Could you pastebin the complete error? You've only given part of it.

**Comment by xknat** [comment]
maar natuurlijk! moment gedult

**Comment by xknat** [comment]
:$ woops
