### ISSUE TITLE
Couldn't execute SQLite statement

### ISSUE THREAD

**Issue by TheChampTF** [Staartvin/Statz#50]
Happens on latest dev build http://paste.yu8.me/?5cbddff5763c2c84#A+US0sp1lxad1uPnLZd3V7FxPutII+wvOUU5LoSMpTA=

**Comment by Staartvin** [comment]
Could you provide your db file?

**Comment by TheChampTF** [comment]
https://www.sendspace.com/file/eyqczl

**Comment by Staartvin** [comment]
What version were you on before you upgraded to the latest dev build?

**Comment by TheChampTF** [comment]
Latest released

**Comment by Staartvin** [comment]
Does the issue still persist in Statz v1.4.5?

**Comment by TheChampTF** [comment]
Currently not active in the Minecraft world. But will let you know if I find any problems, if I get back to it.
