### ISSUE TITLE
I need a help with MySQL and PHP

### ISSUE THREAD

**Issue by EncryptSL** [Staartvin/Statz#55]
Hello I have a question I need to help out listing data such as voting in php. Could you help me if it was possible?
I've never done a listing of mysql data in tables.

Sorry for my English.

I want write data from MySQL on php.

Thx for answer.

**Comment by Staartvin** [comment]
There are a lot of tutorials on reading data from a MySQL database using PHP. Try this one: https://www.w3schools.com/php/php_mysql_intro.asp
