### ISSUE TITLE
Problem with statz and autorank

### ISSUE THREAD

**Issue by vergara2090** [Staartvin/Statz#59]
Hello, I have AutoRank 4.0.5 and Statz 1.4.3, but the statistics of the players do not appear, they do not rise in rank either. When using the / ar hooks or / Statz hooks command, the list of plugins appears.

**Comment by Staartvin** [comment]
What happens when you perform **/statz list**?

**Comment by vergara2090** [comment]
It only shows 
----------------- [Statz of (player)] ------------

**Comment by vergara2090** [comment]
In the console it says:
24.11 15:42:53 [Server] INFO [Statz debug] Save Statz database.
24.11 15:42:43 [Server] INFO [Autorank DEBUG] Obtaining fresh global time of '2b2f9967-dc66-3512-a693-02a8172f34b2'
24.11 15:42:43 [Server] INFO [Statz debug] Save Statz database.
24.11 15:42:43 [Server] INFO [Autorank DEBUG] Obtaining fresh global time of '4d16465e-dcd6-384d-b8dc-60dfa707a9a7'
24.11 15:42:42 [Server] INFO [Autorank DEBUG] Using Essentials for AFK
24.11 15:42:42 [Server] INFO [Autorank DEBUG] Using Essentials for AFK
24.11 15:42:42 [Server] INFO [Autorank DEBUG] Checking players for automatic ranking
24.11 15:42:33 [Server] INFO [Statz debug] Save Statz database.
24.11 15:42:23 [Server] INFO [Statz debug] Save Statz database.


I think that shows the plugin is updating the database.

**Comment by Golvore** [comment]
You need Statz 1.4.4 https://www.spigotmc.org/resources/statz.25969/ and Plugin Library https://www.spigotmc.org/resources/plugin-library.17645/
