### ISSUE TITLE
I Cant Add Statz To My Plugin Folder!

### ISSUE THREAD

**Issue by ItsJustaTest** [Staartvin/Statz#6]
Basically Im Using Autorank  and i need Statz for it to work! please help!  also I'm not hosting of my PC I bought a server! so if any1 could find out how to do it i would like to know please.
Thanks

**Comment by Staartvin** [comment]
Do you know how to add a plugin to your plugins folder?

**Comment by ItsJustaTest** [comment]
yes but i dont know how to add this one

**Comment by ItsJustaTest** [comment]
When i tryed adding the folder to my plugins it wont allow me

**Comment by Staartvin** [comment]
Do you use a server host?

**Comment by ItsJustaTest** [comment]
Well I Bought One im hosting of MineSpan

**Comment by ItsJustaTest** [comment]
how do i add the plugin into my folder witch one is the right one?

**Comment by ItsJustaTest** [comment]
on autorank peoples time are not going up how do i fix it?

**Comment by Staartvin** [comment]
Do you have any error log?

**Comment by heckabecca** [comment]
Ok I got this. I use Minespan too.

You need to use an FTP Client.
I use : https://filezilla-project.org/

Once you download and isntall the program, you will see at the top "Host:
____ Username:____ Password:____ Port:____ Quickconnect"

Fill in your log in info. Which is found in the Minespan Server panel >
Files > FTP File Access
Click "Quickconnect" and it will connect you to your sever and bring up all
the files and folders.

That's where you can upload the plugin to the correct location.

**Comment by Staartvin** [comment]
Thanks a bunch @heckabecca !
