### ISSUE TITLE
STATZ MESSAGE ERROR ON CONSOLE

### ISSUE THREAD

**Issue by Golvore** [Staartvin/Statz#60]
I get this error https://hastebin.com/ufexalizah.sql some times on console

**Comment by Golvore** [comment]
https://hastebin.com/itovikuwak.sql

**Comment by Staartvin** [comment]
Do you know when you get this error?

**Comment by Golvore** [comment]
Many times, when the server has been on for a long time.

**Comment by leventinio** [comment]
Helly, i have the same Problem, after a time the Server is crashing.

https://hastebin.com/ruquyidotu.md

**Comment by Swede37** [comment]
I've been getting this as well. If someone could even tell me just how big that column needed to be, It could be manually adjusted?

Using:
-MySQL for storage
-Statz v1.4.5
-Spigot-4bd94dc-fd702e4 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
-Autorank v4.1

I'm also starting to get "duplicate error " messages as well now

**Comment by Swede37** [comment]
I've been getting this as well. If someone could even tell me just how big that column needed to be, It could be manually adjusted?

Using:
-MySQL for storage
-Statz v1.4.5
-Spigot-4bd94dc-fd702e4 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
-Autorank v4.1

**Comment by Staartvin** [comment]
I can't seem to read any of the links that you provide. Can somebody provide me a screenshot of the error?
