### ISSUE TITLE
Use BattleLevels kill count as requirement.

### ISSUE THREAD

**Issue by Golvore** [Staartvin/Statz#63]
Please add support for BattleLevels Statz and BattleLevels have a different count system

**Comment by Staartvin** [comment]
Statz already supports BattleLevels if you download the PluginLibrary extension!

**Comment by Golvore** [comment]
autorank only sees the kills of statz and ignores those of battlelevels.

**Comment by Golvore** [comment]
statz counts the direct murders, but battlelevels all of them (for example, that a user pushes another from very high and this one dies because of him, this counts as kill for the user)

**Comment by Staartvin** [comment]
Hmm that's a good one. Perhaps I can add a requirement that directly taps it from battle levels

**Comment by Golvore** [comment]
when?

**Comment by Staartvin** [comment]
Wait, is this not a suggestion for Autorank instead of Statz?

**Comment by Staartvin** [comment]
This is a suggestion for Autorank. so this is not the right place to host the enhancement.
