### ISSUE TITLE
Crafted Items Recording Wrong

### ISSUE THREAD

**Issue by heckabecca** [Staartvin/Statz#68]
Hey there! Its been a while that this has been an issue, and not sure your aware. But when crafting items, Statz is not recording it right. If someone crafts multiple items at once by holding the left-shift then clicking the crafted item, it will only count it as 1 item crafted instead of the actual number that was crafted. 

Example: If someone wants to take a gold block and craft 9 ingots from it, instead of it calculating as 9, it only calculates as 1 item crafted. Unless the time is taken to avoid the left-shift and click for each ingot crafted.

I use Autorank and Statz for my job ranks, which have crafting requirements. This miscalculation makes reaching the crafting requirement much longer than it should...

I really hope this makes sense and you understand what I'm talking about. Thanks for looking into it and hope it will be an easy fix.

**Comment by Staartvin** [comment]
Thank you for notifying me about this. I did not know that this was an issue! I will work on fixing this. There are also a few other changes in the pipeline, which I can work on in parallel.

**Comment by heckabecca** [comment]
Thank you! Looking forward to the update :)
