### ISSUE TITLE
Database connection error

### ISSUE THREAD

**Issue by Guddina-tim** [Staartvin/Statz#70]
Hello,

I just connected Statz to a MySQL database, and I'm now getting this error repeated throughout the console: 

https://pastebin.com/XwQG4vjT

**Comment by Staartvin** [comment]
Is your MySQL database up and running? Is it accessible by other plugins? Are the credentials you entered correct?

**Comment by Guddina-tim** [comment]
I just used BlueStats to connect to the same database. Same credentials copied and pasted. Looking in the Database I see all of the Statz tables were created. Every player who has logged in can be seen in BlueStats, which gets the data from Statz. 

http://treecrafters.online/stats/highscores/

**Comment by Staartvin** [comment]
Hmm, when do these errors pop up exactly? When you turn on the server?

**Comment by Guddina-tim** [comment]
They're happening every few minutes. I just looked again and saw the same errors repeating over the course of several minutes. https://pastebin.com/D0HUZ2AG

**Comment by Guddina-tim** [comment]
Something that's especially strange is that Statz is actually sending some data into the database. I just tested it by placing and emptying 10 buckets, and Bluestats immediately got the data from Statz and displayed it here: http://treecrafters.online/stats/highscores/

**Comment by Staartvin** [comment]
I see this error: _java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost._

**Comment by Staartvin** [comment]
What is the **_bind-address_** option in your .ini file?

**Comment by Guddina-tim** [comment]
Sorry, I'll need a little help, here. Which .ini file? I'm running a Centos 7 VPS, so I can get to any file, but I'm guessing you don't mean php.ini , heh

**Comment by Guddina-tim** [comment]
Probably my.ini - I don't actually have the MySQL server set up on the same machine as the minecraft server. I'll need to do some digging to see if I can find that.

**Comment by Staartvin** [comment]
If you're running a windows server, then it's my.ini file located in the _ProgramData_ folder (generally).

**Comment by Guddina-tim** [comment]
Is there a way to reload Statz without restarting the server?

**Comment by Staartvin** [comment]
No, there is not. If you're running on a production server, it might be good to set up a test server where we can start/stop the server often.

**Comment by Guddina-tim** [comment]
That's fine. I was just curious. 

I just tried directly connecting to the IP address for the MySQL server instead of the hostname which that server host gives me to use. I do not yet know what the bind-address is, as I'm waiting to hear back from the host with that answer. It could be the same IP address I just attempted to connect to, though. I'll need to wait to confirm.

**Comment by Guddina-tim** [comment]
Alright, I got this resolved. I reinstalled MySQL, re-created databases, Statz, and BlueStats and now I'm not getting any errors. Not sure what the issue was, still, but at least it's resolved now after a couple hours of re-installation.

**Comment by Staartvin** [comment]
Very good to hear that you got it resolved, but it's not nice to hear that it took a reinstall to get it working. There must be some setting that had to be changed and got defaulted when reinstalling your Mysql database
