### ISSUE TITLE
MySQL error - truncated data

### ISSUE THREAD

**Issue by stifflered** [Staartvin/Statz#73]
Shows up when I try to log in and then am immediately kicked.

`04.05 16:41:40 [Server] ERROR [Statz] Couldn't execute MySQL statement:
04.05 16:41:40 [Server] INFO java.sql.BatchUpdateException: Data truncation: Data too long for column 'reason' at row 1
04.05 16:41:40 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_141]
04.05 16:41:40 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_141]
04.05 16:41:40 [Server] INFO at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_141]
04.05 16:41:40 [Server] INFO at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_141]
04.05 16:41:40 [Server] INFO at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[spigot-latest.jar:git-Spigot-2086bb0-1988d7f]
04.05 16:41:40 [Server] INFO at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[spigot-latest.jar:git-Spigot-2086bb0-1988d7f]
04.05 16:41:40 [Server] INFO at com.mysql.jdbc.SQLError.createBatchUpdateException(SQLError.java:1163) ~[spigot-latest.jar:git-Spigot-2086bb0-1988d7f]
04.05 16:41:40 [Server] INFO at com.mysql.jdbc.StatementImpl.executeBatchInternal(StatementImpl.java:1060) ~[spigot-latest.jar:git-Spigot-2086bb0-1988d7f]
04.05 16:41:40 [Server] INFO at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:970) ~[spigot-latest.jar:git-Spigot-2086bb0-1988d7f]
04.05 16:41:40 [Server] INFO at me.staartvin.statz.database.MySQLConnector.setBatchObjects(MySQLConnector.java:967) [Statz-1.5.1.jar:?]
04.05 16:41:40 [Server] INFO at me.staartvin.statz.tasks.UpdateDatabaseTask.run(UpdateDatabaseTask.java:81) [Statz-1.5.1.jar:?]
04.05 16:41:40 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) [spigot-latest.jar:git-Spigot-2086bb0-1988d7f]
04.05 16:41:40 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-latest.jar:git-Spigot-2086bb0-1988d7f]
04.05 16:41:40 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_141]
04.05 16:41:40 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_141]
04.05 16:41:40 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
04.05 16:41:40 [Server] INFO Caused by: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'reason' at row 1
04.05 16:41:40 [Server] INFO at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3971) ~[spigot-latest.jar:git-Spigot-2086bb0-1988d7f]
04.05 16:41:40 [Server] INFO at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909) ~[spigot-latest.jar:git-Spigot-2086bb0-1988d7f]
04.05 16:41:40 [Server] INFO at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527) ~[spigot-latest.jar:git-Spigot-2086bb0-1988d7f]
04.05 16:41:40 [Server] INFO at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680) ~[spigot-latest.jar:git-Spigot-2086bb0-1988d7f]
04.05 16:41:40 [Server] INFO at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2480) ~[spigot-latest.jar:git-Spigot-2086bb0-1988d7f]
04.05 16:41:40 [Server] INFO at com.mysql.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1552) ~[spigot-latest.jar:git-Spigot-2086bb0-1988d7f]
04.05 16:41:40 [Server] INFO at com.mysql.jdbc.StatementImpl.executeBatchInternal(StatementImpl.java:1034) ~[spigot-latest.jar:git-Spigot-2086bb0-1988d7f]
04.05 16:41:40 [Server] INFO ... 8 more`

**Comment by Guddina-tim** [comment]
I had a similar issue pop up like this one. Not sure if I should create a new ticket or not since this issue hasn't been marked as resolved yet. Here's the new error:

https://pastebin.com/qFLKP4Tb

**Comment by Staartvin** [comment]
Are you getting this frequently?

**Comment by Staartvin** [comment]
When do you get that error? During log in?

**Comment by Guddina-tim** [comment]
It happened while I was online AFK. Another player was doing their normal build stuff. Then I logged out and I looked in the console and saw the error.

**Comment by Staartvin** [comment]
It seems that it happens after you type a long command. Can you try to do this and see if you indeed get the error?

**Comment by Guddina-tim** [comment]
Yes. This seems accurate.

**Comment by Staartvin** [comment]
Good. I can start fixing this bug.
