### ISSUE TITLE
Exception while executing task 54

### ISSUE THREAD

**Issue by Sayumiii** [Staartvin/Statz#78]
This error appears about a minute into the server starting, and makes it impossible for the database to update afterwards.

`05.06 18:51:55 [Server] WARN Plugin Statz v1.5.1 generated an exception while executing task 54
05.06 18:51:55 [Server] INFO java.util.ConcurrentModificationException: null
05.06 18:51:55 [Server] INFO at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901) ~[?:1.8.0_131]
05.06 18:51:55 [Server] INFO at java.util.ArrayList$Itr.next(ArrayList.java:851) ~[?:1.8.0_131]
05.06 18:51:55 [Server] INFO at me.staartvin.statz.update.UpdatePoolManager.getUpdateQueriesCopy(UpdatePoolManager.java:87) ~[?:?]
05.06 18:51:55 [Server] INFO at me.staartvin.statz.tasks.UpdateDatabaseTask.run(UpdateDatabaseTask.java:41) ~[?:?]
05.06 18:51:55 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-7754231-9a1f5ee]
05.06 18:51:55 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot.jar:git-Spigot-7754231-9a1f5ee]
05.06 18:51:55 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
05.06 18:51:55 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
05.06 18:51:55 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]`

Any attempted database updates after this error result in:

`05.06 18:53:25 [Server] INFO Skip database sync as there is still one running.`

Any help would be greatly appreciated!

**Comment by Staartvin** [comment]
I'm aware of this issue, but thanks for reporting it. I'll close this issue as it is a duplicate, but please follow [this issue](https://github.com/Staartvin/Statz/issues/76).

**Comment by cheeseries** [comment]
These links lead me in circles. Is there a solution for this?
