### ISSUE TITLE
Online status

### ISSUE THREAD

**Issue by Vilican** [Staartvin/Statz#8]
Please add function which allows to detect if player is online. Like:

`Server <---> MySQL <---> Web app`

Thanks

**Comment by Staartvin** [comment]
What do you mean?

**Comment by Vilican** [comment]
I mean that I would like to display on my server website (web-app) if the player is online or not.

So it would be great if you added onPlayerJoin event MySQL set online = 1 and onPlayerQuit event MySQL set online = 0.

**Comment by ChromaHosting** [comment]
would be a usefull addition, i would deffinately use it
