### ISSUE TITLE
1.5.1 cant read DB

### ISSUE THREAD

**Issue by CaszGamerMD** [Staartvin/Statz#81]
statz 1.5.1 clears my statz and wont load/ return statz, no errors are in the console it just won't read my database.
after i reload with 1.4.5 everything is normal again and values are back

i've even cleared /plugins of the old statz before putting in new, and ran around doing things and still couldnt pull numbers for me.

**Comment by Staartvin** [comment]
Can you try this version: http://178.62.255.148:8080/job/Statz/49/

**Comment by CaszGamerMD** [comment]
Loading it currently.. 1st with old statz folder still there
can see old info, custom list doesnt work.

**Comment by CaszGamerMD** [comment]
*side note* the dev build wouldnt let me use papi with it.
