### ISSUE TITLE
Statz error on server startup

### ISSUE THREAD

**Issue by AshtonMemer** [Staartvin/Statz#87]
Error Message: https://pastebin.com/raw/QgCReXLi
I am using Statz for Autorank, but everytime I start the server, I get this error message. I was looking for any dependencies i missed, but nothing. The plugin is up to date as well. I am running the final spigot 1.12.2 build.

**Comment by Slimerblue22** [comment]
Same error, also in 1.12.2 :/

**Comment by AshtonMemer** [comment]
@Slimerblue22 Ah that worked, thanks.
