### ISSUE TITLE
Message spaming log since 1.5.3 upgrade 

### ISSUE THREAD

**Issue by NoWing31** [Staartvin/Statz#90]
Context : 
PaperSpigot 1.13.1 
Statz 1.5.3 

Problem : 
Since 1.5.3 update I've this message spaming the logs :

_> [20:20:38] [Craft Scheduler Thread - 10/ERROR]: [Statz] Couldn't execute MySQL statement:
> --
> java.sql.BatchUpdateException: Field 'typeid' doesn't have a default value
> at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_101]
> at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_101]
> at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_101]
> at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_101]
> at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[patched_1.13.1.jar:git-Paper-332]
> at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[patched_1.13.1.jar:git-Paper-332]
> at com.mysql.jdbc.SQLError.createBatchUpdateException(SQLError.java:1163) ~[patched_1.13.1.jar:git-Paper-332]
> at com.mysql.jdbc.StatementImpl.executeBatchInternal(StatementImpl.java:1060) ~[patched_1.13.1.jar:git-Paper-332]
> at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:970) ~[patched_1.13.1.jar:git-Paper-332]
> at me.staartvin.statz.database.MySQLConnector.setBatchObjects(MySQLConnector.java:961) ~[?:?]
> at me.staartvin.statz.tasks.UpdateDatabaseTask.run(UpdateDatabaseTask.java:81) ~[?:?]
> at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.13.1.jar:git-Paper-332]
> at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.1.jar:git-Paper-332]
> at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.1.jar:git-Paper-332]
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
> at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
> Caused by: java.sql.SQLException: Field 'typeid' doesn't have a default value
> at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965) ~[patched_1.13.1.jar:git-Paper-332]
> at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976) ~[patched_1.13.1.jar:git-Paper-332]
> at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912) ~[patched_1.13.1.jar:git-Paper-332]
> at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530) ~[patched_1.13.1.jar:git-Paper-332]
> at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683) ~[patched_1.13.1.jar:git-Paper-332]
> at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2482) ~[patched_1.13.1.jar:git-Paper-332]
> at com.mysql.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1552) ~[patched_1.13.1.jar:git-Paper-332]
> at com.mysql.jdbc.StatementImpl.executeBatchInternal(StatementImpl.java:1034) ~[patched_1.13.1.jar:git-Paper-332]
> 
> 
>_ 
Thank you for your help

**Comment by Staartvin** [comment]
Try the latest version of Statz and report back if the issue still arises!
