### ISSUE TITLE
Building Statz Failure Due To Downloading Dependencies

### ISSUE THREAD

**Issue by ThePieMonster** [Staartvin/Statz#98]
I was trying to build the project from the source but noticed that there are requirements that are being downloaded from http://62.131.38.74:8081/artifactory/... which fail. Are you hosting something yourself? You should consider hosting on Raw GitHub or another more reliable source. 

Log from Eclipse "Maven Install"
> [INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for me.staartvin.Statz:Statz:jar:1.5.3-Dev-${BUILD_NUMBER}
[WARNING] 'version' contains an expression but should be a constant. @ line 6, column 11
[WARNING] 'dependencies.dependency.version' for me.staartvin:PluginLibrary:jar is either LATEST or RELEASE (both of them are being deprecated) @ line 135, column 22
[WARNING] 'build.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.apache.maven.plugins:maven-compiler-plugin @ line 52, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] 
[INFO] ----------------------< me.staartvin.Statz:Statz >----------------------
[INFO] Building Statz 1.5.3-Dev-${BUILD_NUMBER}
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] Downloading from : http://62.131.38.74:8081/artifactory/ext-release-local/org/spigotmc/spigot-api/1.13-R0.1-SNAPSHOT/maven-metadata.xml
[INFO] Downloading from : https://raw.github.com/rlf/uSkyBlock/mvn-repo/org/spigotmc/spigot-api/1.13-R0.1-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata org.spigotmc:spigot-api:1.13-R0.1-SNAPSHOT/maven-metadata.xml from/to staartvin-repo (http://62.131.38.74:8081/artifactory/ext-release-local/): connect timed out
[WARNING] Failure to transfer org.spigotmc:spigot-api:1.13-R0.1-SNAPSHOT/maven-metadata.xml from http://62.131.38.74:8081/artifactory/ext-release-local/ was cached in the local repository, resolution will not be reattempted until the update interval of staartvin-repo has elapsed or updates are forced. Original error: Could not transfer metadata org.spigotmc:spigot-api:1.13-R0.1-SNAPSHOT/maven-metadata.xml from/to staartvin-repo (http://62.131.38.74:8081/artifactory/ext-release-local/): connect timed out
[INFO] Downloading from : https://raw.github.com/rlf/uSkyBlock/mvn-repo/net/md-5/bungeecord-chat/1.13-SNAPSHOT/maven-metadata.xml
[INFO] Downloading from : http://62.131.38.74:8081/artifactory/ext-release-local/net/md-5/bungeecord-chat/1.13-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata net.md-5:bungeecord-chat:1.13-SNAPSHOT/maven-metadata.xml from/to staartvin-repo (http://62.131.38.74:8081/artifactory/ext-release-local/): connect timed out
[WARNING] Failure to transfer net.md-5:bungeecord-chat:1.13-SNAPSHOT/maven-metadata.xml from http://62.131.38.74:8081/artifactory/ext-release-local/ was cached in the local repository, resolution will not be reattempted until the update interval of staartvin-repo has elapsed or updates are forced. Original error: Could not transfer metadata net.md-5:bungeecord-chat:1.13-SNAPSHOT/maven-metadata.xml from/to staartvin-repo (http://62.131.38.74:8081/artifactory/ext-release-local/): connect timed out
[INFO] Downloading from : http://62.131.38.74:8081/artifactory/ext-release-local/net/md-5/bungeecord-parent/1.13-SNAPSHOT/maven-metadata.xml
[INFO] Downloading from : https://raw.github.com/rlf/uSkyBlock/mvn-repo/net/md-5/bungeecord-parent/1.13-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata net.md-5:bungeecord-parent:1.13-SNAPSHOT/maven-metadata.xml from/to staartvin-repo (http://62.131.38.74:8081/artifactory/ext-release-local/): connect timed out
[INFO] Downloading from : http://62.131.38.74:8081/artifactory/ext-release-local/org/bukkit/bukkit/1.13-R0.1-SNAPSHOT/maven-metadata.xml
[INFO] Downloading from : https://raw.github.com/rlf/uSkyBlock/mvn-repo/org/bukkit/bukkit/1.13-R0.1-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata org.bukkit:bukkit:1.13-R0.1-SNAPSHOT/maven-metadata.xml from/to staartvin-repo (http://62.131.38.74:8081/artifactory/ext-release-local/): connect timed out
[WARNING] Failure to transfer org.bukkit:bukkit:1.13-R0.1-SNAPSHOT/maven-metadata.xml from http://62.131.38.74:8081/artifactory/ext-release-local/ was cached in the local repository, resolution will not be reattempted until the update interval of staartvin-repo has elapsed or updates are forced. Original error: Could not transfer metadata org.bukkit:bukkit:1.13-R0.1-SNAPSHOT/maven-metadata.xml from/to staartvin-repo (http://62.131.38.74:8081/artifactory/ext-release-local/): connect timed out
[INFO] Downloading from : http://62.131.38.74:8081/artifactory/ext-release-local/com/vexsoftware/votifier/1.9/votifier-1.9.pom
[INFO] Downloading from : http://62.131.38.74:8081/artifactory/ext-release-local/nl/lolmewn/stats/Stats/3.1.2-SNAPSHOT/Stats-3.1.2-20171108.195442-1.pom
[INFO] Downloading from : https://raw.github.com/rlf/uSkyBlock/mvn-repo/nl/lolmewn/stats/Stats/3.1.2-SNAPSHOT/Stats-3.1.2-20171108.195442-1.pom
[WARNING] The POM for net.milkbowl.vault:Vault:jar:1.5.6 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[INFO] Downloading from : http://62.131.38.74:8081/artifactory/ext-release-local/com/vexsoftware/nuvotifier-universal/2.3.2.2/nuvotifier-universal-2.3.2.2.pom
[INFO] Downloading from : http://62.131.38.74:8081/artifactory/ext-release-local/me/staartvin/PluginLibrary/maven-metadata.xml
[INFO] Downloading from : https://raw.github.com/rlf/uSkyBlock/mvn-repo/me/staartvin/PluginLibrary/maven-metadata.xml
[WARNING] Could not transfer metadata me.staartvin:PluginLibrary/maven-metadata.xml from/to staartvin-repo (http://62.131.38.74:8081/artifactory/ext-release-local/): connect timed out
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 13:21 min
[INFO] Finished at: 2019-01-26T18:05:11-08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project Statz: Could not resolve dependencies for project me.staartvin.Statz:Statz:jar:1.5.3-Dev-${BUILD_NUMBER}: Failed to collect dependencies at com.vexsoftware:votifier:jar:1.9: Failed to read artifact descriptor for com.vexsoftware:votifier:jar:1.9: Could not transfer artifact com.vexsoftware:votifier:pom:1.9 from/to staartvin-repo (http://62.131.38.74:8081/artifactory/ext-release-local/): connect timed out -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by Staartvin** [comment]
Please try the latest version of Statz as I've changed to a different building server and artifact storage.
